# Blockhost Provisioner Project Manifest
# Machine-readable overview for integration and automation
# Last updated: 2026-02-05 (end-to-end testing fixes)

name: blockhost-provisioner
version: "0.2.0"
description: |
  Terraform-based Proxmox VM automation with NFT web3 authentication.
  Creates Debian 12 VMs from a cloud-init template that includes libpam-web3
  for Ethereum wallet-based SSH login.

  This package provides VM provisioning scripts. Configuration and database
  modules are provided by the blockhost-common package.

# Primary entry points for integration
entry_points:
  create_vm:
    script: scripts/vm-generator.py
    description: Generate and optionally apply Terraform config for a new VM
    required_args:
      - name: vm_name
        position: 1
        description: Name for the VM (e.g., web-001)
      - name: --owner-wallet
        description: Ethereum wallet address to receive the access NFT
    optional_args:
      - name: --purpose
        description: Description/purpose of the VM
      - name: --cpu
        type: int
        default: 1
        description: Number of CPU cores
      - name: --memory
        type: int
        default: 512
        description: Memory in MB
      - name: --disk
        type: int
        default: 10
        description: Disk size in GB
      - name: --tags
        type: list
        description: Tags for the VM
      - name: --expiry-days
        type: int
        default: 30
        description: Days until VM expires
      - name: --apply
        type: flag
        description: Run terraform apply after generating config
      - name: --mock
        type: flag
        description: Use mock database for testing
      - name: --user-signature
        description: User's decrypted signature from subscription system (hex)
      - name: --public-secret
        description: Message the user signed during subscription
      - name: --skip-mint
        type: flag
        description: Skip NFT minting (for testing)
      - name: --no-web3
        type: flag
        description: Disable web3 auth, use standard cloud-init
      - name: --cloud-init
        description: Cloud-init template name (default nft-auth when web3 enabled)
      - name: --ip
        description: Specific IPv4 address (otherwise auto-allocated)
      - name: --ipv6
        description: Specific IPv6 address (otherwise auto-allocated from broker pool)
      - name: --node
        description: Proxmox node name (default from terraform.tfvars or 'pve')
      - name: --disk-datastore
        description: Datastore for VM disk (default from terraform.tfvars or 'local-lvm')
      - name: --cloudinit-datastore
        description: Datastore for cloud-init (default from terraform.tfvars or 'local')
    outputs:
      - Generated .tf.json file path
      - Allocated VMID
      - Allocated IPv4 address
      - Allocated IPv6 address (if broker pool configured)
      - Reserved NFT token ID (if web3 enabled)
    example: |
      python3 scripts/vm-generator.py web-001 \
        --owner-wallet 0x1234...abcd \
        --purpose "production web server" \
        --cpu 2 --memory 2048 \
        --apply

  garbage_collection:
    script: scripts/vm-gc.py
    description: |
      Two-phase VM garbage collection:
      Phase 1 (Suspend): Shuts down expired VMs, preserves disk data
      Phase 2 (Destroy): Destroys suspended VMs past grace period
    optional_args:
      - name: --execute
        type: flag
        description: Actually perform actions (default is dry run)
      - name: --suspend-only
        type: flag
        description: Only run Phase 1 (suspend expired VMs)
      - name: --destroy-only
        type: flag
        description: Only run Phase 2 (destroy past-grace VMs)
      - name: --grace-days
        type: int
        description: Override grace period from config (days after expiry before destroy)
      - name: --mock
        type: flag
        description: Use mock database for testing
      - name: --verbose
        type: flag
        description: Verbose output
    systemd_timer:
      timer_file: systemd/blockhost-gc.timer
      service_file: systemd/blockhost-gc.service
      schedule: Daily at 2:00 AM with up to 30 minutes randomized delay
    example: |
      # Dry run both phases
      python3 scripts/vm-gc.py

      # Execute both phases
      python3 scripts/vm-gc.py --execute

      # Only suspend expired VMs
      python3 scripts/vm-gc.py --execute --suspend-only

      # Check timer status
      systemctl status blockhost-gc.timer

  resume_vm:
    script: scripts/vm-resume.py
    description: Resume a suspended VM, restoring it to active status
    required_args:
      - name: vm_name
        position: 1
        description: Name of the VM to resume
    optional_args:
      - name: --extend-days
        type: int
        description: Extend expiry by this many days (default from config)
      - name: --mock
        type: flag
        description: Use mock database for testing
      - name: --dry-run
        type: flag
        description: Show what would be done without making changes
    example: |
      # Resume a suspended VM
      blockhost-vm-resume myvm

      # Resume and extend expiry by 30 days
      blockhost-vm-resume myvm --extend-days 30

  mint_nft:
    script: scripts/mint_nft.py
    description: Mint access credential NFT to a wallet
    required_args:
      - name: --owner-wallet
        description: Wallet address to receive the NFT
      - name: --machine-id
        description: VM name/machine ID (used in NFT description)
    optional_args:
      - name: --user-encrypted
        description: Hex-encoded encrypted connection details (default 0x)
      - name: --public-secret
        description: Message the user signed during subscription
      - name: --dry-run
        type: flag
        description: Print command without executing
    example: |
      python3 scripts/mint_nft.py --owner-wallet 0x1234... --machine-id web-001 \
        --user-encrypted 0xabc... --public-secret "libpam-web3:0x1234...:12345"

  build_template:
    script: scripts/build-template.sh
    description: Build and deploy Debian 12 template with libpam-web3 to Proxmox
    environment_vars:
      - name: PROXMOX_HOST
        default: root@ix
        description: SSH target for Proxmox host
      - name: TEMPLATE_VMID
        default: "9001"
        description: VMID for the template
      - name: STORAGE
        default: local-lvm
        description: Proxmox storage for VM disks
      - name: LIBPAM_WEB3_DEB
        default: ~/projects/libpam-web3/packaging/libpam-web3_0.2.0_amd64.deb
        description: Path to libpam-web3 .deb package
    prerequisites:
      - libguestfs-tools (virt-customize)
      - SSH access to Proxmox host
      - libpam-web3 .deb package
    example: |
      PROXMOX_HOST=root@pve ./scripts/build-template.sh

# Python module API (for programmatic use)
python_api:
  mint_nft:
    module: scripts/mint_nft.py
    functions:
      - name: mint_nft
        signature: mint_nft(owner_wallet, machine_id, user_encrypted="0x", public_secret="", config=None, dry_run=False) -> Optional[str]
        description: Mint access NFT with embedded signing page, returns transaction hash
        requires:
          - Foundry (cast CLI)
          - Deployer private key with funds
          - Signing page HTML (from libpam-web3-tools)
      - name: load_signing_page
        signature: load_signing_page(config, user_encrypted="", public_secret="") -> str
        description: Load signing page HTML, embed decrypt credentials if provided, return as base64

# Configuration and database modules are provided by blockhost-common
# See: from blockhost.config import load_db_config, load_web3_config, get_terraform_dir
# See: from blockhost.vm_db import get_database, VMDatabase, MockVMDatabase
external_modules:
  blockhost_common:
    package: blockhost-common
    provides:
      - blockhost.config: Path constants, config loading (load_db_config, load_web3_config, get_terraform_dir, load_broker_allocation)
      - blockhost.vm_db: Database classes (VMDatabase, MockVMDatabase, get_database) with allocate_ip and allocate_ipv6
    config_files:
      - /etc/blockhost/db.yaml
      - /etc/blockhost/web3-defaults.yaml
      - /etc/blockhost/blockhost.yaml
      - /etc/blockhost/broker-allocation.json  # Created by blockhost-broker client, provides IPv6 prefix
      - /var/lib/blockhost/terraform/terraform.tfvars  # Proxmox node, datastore settings

# Cloud-init templates
cloud_init_templates:
  - name: nft-auth
    path: cloud-init/templates/nft-auth.yaml
    description: NFT authentication with web3-auth-svc and signing page
    variables:
      - VM_NAME
      - VM_IP          # IPv4 address (private)
      - VM_IPV6        # IPv6 address (public, may be empty if no broker pool)
      - SIGNING_HOST   # Host for signing URL ([ipv6] or ipv4)
      - USERNAME
      - NFT_TOKEN_ID
      - CHAIN_ID
      - NFT_CONTRACT
      - RPC_URL
      - OTP_LENGTH
      - OTP_TTL
      - SECRET_KEY    # Random 64-char hex for PAM module (generated by vm-generator.py)
      - SSH_KEYS
    behavior:
      ssh_config: |
        SSH is configured for web3-only authentication via /etc/ssh/sshd_config.d/web3-only.conf.
        Pubkey and password auth are disabled; only keyboard-interactive (PAM) is allowed.
      signing_page_startup: |
        The signing page service (web3-sign.service) polls the blockchain
        for NFT existence before starting. This handles the race condition
        where the VM boots before the NFT is minted (minting happens after
        terraform apply succeeds). Timeout: 5 minutes, poll interval: 5 seconds.
        The signing page is fetched from the NFT's tokenURI metadata (animation_url field)
        and served via a Python HTTP server on port 8080.

  - name: webserver
    path: cloud-init/templates/webserver.yaml
    description: Basic webserver with nginx

  - name: devbox
    path: cloud-init/templates/devbox.yaml
    description: Development environment with common tools

# External dependencies
dependencies:
  packages:
    - blockhost-common: Config and database modules (including IPv6 allocation)
    - blockhost-broker: IPv6 tunnel broker (broker-client creates /etc/blockhost/broker-allocation.json)
    - libpam-web3-tools: Signing page HTML, pam_web3_tool CLI
  system:
    - terraform: ">=1.0"
    - libguestfs-tools: For virt-customize
    - foundry: For cast CLI (NFT minting)
  python:
    - pyyaml: YAML parsing (from blockhost-common)
  proxmox:
    - provider: bpg/proxmox >=0.50.0
    - template_vmid: 9001 (Debian 12 with libpam-web3)

# Integration notes
integration:
  as_package:
    description: |
      This package is designed to be installed alongside blockhost-common.
      Install both packages, then configure /etc/blockhost/ config files.
    setup_steps:
      - Install blockhost-common package (provides config modules)
      - Install blockhost-provisioner package (provides this package)
      - Install libpam-web3-tools package (provides signing page)
      - Run init-server.sh from blockhost-engine to generate keys and config
      - Configure /etc/blockhost/db.yaml with terraform_dir path
      - Configure /etc/blockhost/web3-defaults.yaml with contract details
      - Run build-template.sh to deploy template to Proxmox
    usage: |
      # Create VM with web3 auth
      blockhost-vm-create myvm --owner-wallet 0x... --apply

  terraform_state:
    location: Configured via terraform_dir in /etc/blockhost/db.yaml
    note: Generated .tf.json files are written to terraform_dir

# VM Status Lifecycle
vm_lifecycle:
  statuses:
    - active: VM is running and accessible
    - suspended: VM shut down (expired but within grace period), disk preserved
    - destroyed: VM and disk removed, database entry marked
  transitions:
    - "active -> suspended": Via vm-gc.py Phase 1 (when VM expires)
    - "suspended -> active": Via vm-resume.py (when subscription extended)
    - "suspended -> destroyed": Via vm-gc.py Phase 2 (when grace period ends)
  grace_period:
    description: |
      After a VM expires, it enters a grace period before destruction.
      During this time, the VM is suspended (shut down but disk preserved).
      Users can extend their subscription to resume the VM.
    config_key: gc_grace_days (in /etc/blockhost/db.yaml)
    default: 7 days

# Data flow
workflow:
  vm_creation:
    steps:
      - 1: Get next NFT token ID from contract totalSupply() (fallback to database)
      - 2: Allocate VMID, IPv4 and IPv6 (db.allocate_vmid, db.allocate_ip, db.allocate_ipv6)
      - 3: Load Proxmox settings from terraform.tfvars (node, datastores)
      - 4: Render cloud-init template with variables (including SIGNING_HOST for IPv6 or IPv4)
      - 5: Generate .tf.json config (with dual-stack IPv4/IPv6, datastore_id in initialization)
      - 6: Run terraform apply (if --apply)
      - 7: If --user-signature provided, encrypt connection details (pam_web3_tool encrypt-symmetric)
      - 8: Mint NFT to owner wallet (if successful and not --skip-mint)
      - 9: Mark NFT as minted in database
    on_failure:
      - Mark NFT token as failed (not minted, can't reuse ID)
      - VM not created, resources released
    ipv6_notes:
      description: |
        IPv6 addresses are allocated from the broker pool (/etc/blockhost/broker-allocation.json).
        If the broker allocation file exists, VMs get both private IPv4 and public IPv6.
        The NFT encrypted connection details use IPv6 (public) when available.
        The signing page URL also uses IPv6 for internet accessibility.
    encryption_workflow:
      description: |
        When --user-signature is provided, connection details are encrypted into the NFT.
        The user can later decrypt them by re-signing the same message.
      encryption_method: AES-256-GCM with key = keccak256(user_signature)
      encrypted_data: '{"hostname": "<IPv6 or IPv4>", "port": 22, "username": "<user>"}'
